### ISSUE TITLE
Crashed with node-red-contrib-gpio installed

### ISSUE THREAD

**Issue by microspace** [urbiworx/node-red-contrib-freeboard#17]
Node-red crashed when https://github.com/monteslu/node-red-contrib-gpio is installed.
Problem is with freeboard because when I uninstall freeboard, node-red does not crash.

Node-RED version: v0.13.1
Node.js  version: v0.10.38

```
5 Apr 12:18:08 - [red] Uncaught Exception:

5 Apr 12:18:08 - TypeError: Object function (entry) {
  return this.indexOf(entry) !== -1;
} has no method 'end'
    at interval (/home/root/node-red/node_modules/node-red-contrib-freeboard/freeboard.js:71:12)
    at wrapper [as _onTimeout] (timers.js:261:14)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by microspace** [comment]
This is another way to send data to freeboard using websockets: https://gist.github.com/dceejay/fb47301b759222e05f84

**Comment by scargill** [comment]
I have the same issue recently and I've had to remove freeboard... it was crashing my new Raspberry Pi 3 Node-Red installation within a minute of turning on Node-Red.... remove freeboard and the problem goes away. I too have GPIO installed - but then I have lots of things installed.
